# in .cargo/config.toml

[unstable]
build-std = ["core", "compiler_builtins"]
build-std-features = ["compiler-builtins-mem"]

[build]
target = "x86_64-myOS.json"

[target.'cfg(target_os = "none")']
runner = "bootimage runner"
